spring.messages.basename=i18n/traducciones
spring.messages.fallback-to-system-locale=false
logging.file.path = /opt/log/
logging.file.name = 24200346E.log	
logging.level.web = DEBUG
logging.level.org.springframework.web=INFO
logging.level.es.uned.aw=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=DEBUG	
logging.level.org.hibernate.type=TRACE
Logging.level.org.hibernate.stat = DEBUG
logging.file=24200346E.log
# Datasource mysql
#spring.datasource.url = jdbc:mysql://localhost:3306/unedaw2024
#spring.datasource.username = root
#spring.datasource.password = Sa.2024
# Datasource HSQLDB (Memoria)
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.url=jdbc:hsqldb:mem:ped2025db;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=create

## Hibernate Properties mysql
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.generate_statistics = true
#server.port=8081
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2
# Datasource H2
#spring.datasource.url=jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.forma_sql=true

